"""persist verification runs

Revision ID: 619961777f49
Revises: 995b0503e4d5
Create Date: 2026-07-12 15:27:37.926745

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "619961777f49"
down_revision: str | Sequence[str] | None = "995b0503e4d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verificationresult",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("result_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("book_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("verdict", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "book_key", name="uq_verificationresult_run_book"),
    )
    op.create_index(op.f("ix_verificationresult_book_key"), "verificationresult", ["book_key"], unique=False)
    op.create_index(op.f("ix_verificationresult_result_id"), "verificationresult", ["result_id"], unique=True)
    op.create_index(op.f("ix_verificationresult_run_id"), "verificationresult", ["run_id"], unique=False)
    op.create_table(
        "verificationrun",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("completed", sa.Integer(), nullable=False),
        sa.Column("counts", sa.JSON(), nullable=True),
        sa.Column("use_llm", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_verificationrun_run_id"), "verificationrun", ["run_id"], unique=True)
    op.create_index(op.f("ix_verificationrun_status"), "verificationrun", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verificationrun_status"), table_name="verificationrun")
    op.drop_index(op.f("ix_verificationrun_run_id"), table_name="verificationrun")
    op.drop_table("verificationrun")
    op.drop_index(op.f("ix_verificationresult_run_id"), table_name="verificationresult")
    op.drop_index(op.f("ix_verificationresult_result_id"), table_name="verificationresult")
    op.drop_index(op.f("ix_verificationresult_book_key"), table_name="verificationresult")
    op.drop_table("verificationresult")
    # ### end Alembic commands ###
