"""initial durable schema

Revision ID: 995b0503e4d5
Revises:
Create Date: 2026-07-12 15:23:25.271466

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "995b0503e4d5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookrecord",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("calibre_book_id", sa.Integer(), nullable=True),
        sa.Column("paperless_document_id", sa.Integer(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(), nullable=False),
        sa.Column("files", sa.JSON(), nullable=True),
        sa.Column("current_metadata", sa.JSON(), nullable=True),
        sa.Column("field_locks", sa.JSON(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bookrecord_book_key"), "bookrecord", ["book_key"], unique=True)
    op.create_index(op.f("ix_bookrecord_calibre_book_id"), "bookrecord", ["calibre_book_id"], unique=False)
    op.create_index(op.f("ix_bookrecord_paperless_document_id"), "bookrecord", ["paperless_document_id"], unique=False)
    op.create_index(op.f("ix_bookrecord_run_id"), "bookrecord", ["run_id"], unique=False)
    op.create_table(
        "change",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=False),
        sa.Column("before_metadata", sa.JSON(), nullable=True),
        sa.Column("after_metadata", sa.JSON(), nullable=True),
        sa.Column("backup_opf_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_change_book_key"), "change", ["book_key"], unique=False)
    op.create_index(op.f("ix_change_run_id"), "change", ["run_id"], unique=False)
    op.create_table(
        "covervisioncache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("response", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_covervisioncache_phash"), "covervisioncache", ["phash"], unique=False)
    op.create_index(op.f("ix_covervisioncache_sha256"), "covervisioncache", ["sha256"], unique=False)
    op.create_table(
        "evidencepackage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("book_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("current", sa.JSON(), nullable=True),
        sa.Column("extracted", sa.JSON(), nullable=True),
        sa.Column("candidates", sa.JSON(), nullable=True),
        sa.Column("snippets", sa.JSON(), nullable=True),
        sa.Column("cover", sa.JSON(), nullable=True),
        sa.Column("risk_flags", sa.JSON(), nullable=True),
        sa.Column("decision", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidencepackage_book_key"), "evidencepackage", ["book_key"], unique=False)
    op.create_index(op.f("ix_evidencepackage_evidence_id"), "evidencepackage", ["evidence_id"], unique=True)
    op.create_index(op.f("ix_evidencepackage_run_id"), "evidencepackage", ["run_id"], unique=False)
    op.create_table(
        "operationledger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("operation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("idempotency_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("operation_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("book_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requested_patch", sa.JSON(), nullable=True),
        sa.Column("before_metadata", sa.JSON(), nullable=True),
        sa.Column("target_metadata", sa.JSON(), nullable=True),
        sa.Column("observed_metadata", sa.JSON(), nullable=True),
        sa.Column("authorization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_operationledger_idempotency_key"),
    )
    op.create_index(op.f("ix_operationledger_authorization_id"), "operationledger", ["authorization_id"], unique=False)
    op.create_index(op.f("ix_operationledger_book_key"), "operationledger", ["book_key"], unique=False)
    op.create_index(op.f("ix_operationledger_operation_id"), "operationledger", ["operation_id"], unique=True)
    op.create_index(op.f("ix_operationledger_operation_type"), "operationledger", ["operation_type"], unique=False)
    op.create_index(op.f("ix_operationledger_run_id"), "operationledger", ["run_id"], unique=False)
    op.create_index(op.f("ix_operationledger_state"), "operationledger", ["state"], unique=False)
    op.create_table(
        "outboxevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("aggregate_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outboxevent_aggregate_id"), "outboxevent", ["aggregate_id"], unique=False)
    op.create_index(op.f("ix_outboxevent_available_at"), "outboxevent", ["available_at"], unique=False)
    op.create_index(op.f("ix_outboxevent_event_id"), "outboxevent", ["event_id"], unique=True)
    op.create_index(op.f("ix_outboxevent_event_type"), "outboxevent", ["event_type"], unique=False)
    op.create_index(op.f("ix_outboxevent_status"), "outboxevent", ["status"], unique=False)
    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metadata_filter", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_run_id"), "run", ["run_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_run_id"), table_name="run")
    op.drop_table("run")
    op.drop_index(op.f("ix_outboxevent_status"), table_name="outboxevent")
    op.drop_index(op.f("ix_outboxevent_event_type"), table_name="outboxevent")
    op.drop_index(op.f("ix_outboxevent_event_id"), table_name="outboxevent")
    op.drop_index(op.f("ix_outboxevent_available_at"), table_name="outboxevent")
    op.drop_index(op.f("ix_outboxevent_aggregate_id"), table_name="outboxevent")
    op.drop_table("outboxevent")
    op.drop_index(op.f("ix_operationledger_state"), table_name="operationledger")
    op.drop_index(op.f("ix_operationledger_run_id"), table_name="operationledger")
    op.drop_index(op.f("ix_operationledger_operation_type"), table_name="operationledger")
    op.drop_index(op.f("ix_operationledger_operation_id"), table_name="operationledger")
    op.drop_index(op.f("ix_operationledger_book_key"), table_name="operationledger")
    op.drop_index(op.f("ix_operationledger_authorization_id"), table_name="operationledger")
    op.drop_table("operationledger")
    op.drop_index(op.f("ix_evidencepackage_run_id"), table_name="evidencepackage")
    op.drop_index(op.f("ix_evidencepackage_evidence_id"), table_name="evidencepackage")
    op.drop_index(op.f("ix_evidencepackage_book_key"), table_name="evidencepackage")
    op.drop_table("evidencepackage")
    op.drop_index(op.f("ix_covervisioncache_sha256"), table_name="covervisioncache")
    op.drop_index(op.f("ix_covervisioncache_phash"), table_name="covervisioncache")
    op.drop_table("covervisioncache")
    op.drop_index(op.f("ix_change_run_id"), table_name="change")
    op.drop_index(op.f("ix_change_book_key"), table_name="change")
    op.drop_table("change")
    op.drop_index(op.f("ix_bookrecord_run_id"), table_name="bookrecord")
    op.drop_index(op.f("ix_bookrecord_paperless_document_id"), table_name="bookrecord")
    op.drop_index(op.f("ix_bookrecord_calibre_book_id"), table_name="bookrecord")
    op.drop_index(op.f("ix_bookrecord_book_key"), table_name="bookrecord")
    op.drop_table("bookrecord")
    # ### end Alembic commands ###
