"""add manual authorizations

Revision ID: f6369c0a2137
Revises: 619961777f49
Create Date: 2026-07-12 15:37:00.434823

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6369c0a2137"
down_revision: str | Sequence[str] | None = "619961777f49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manualauthorization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("authorization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("book_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("verdict_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("patch_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manualauthorization_authorization_id"), "manualauthorization", ["authorization_id"], unique=True
    )
    op.create_index(op.f("ix_manualauthorization_book_key"), "manualauthorization", ["book_key"], unique=False)
    op.create_index(op.f("ix_manualauthorization_patch_hash"), "manualauthorization", ["patch_hash"], unique=False)
    op.create_index(op.f("ix_manualauthorization_run_id"), "manualauthorization", ["run_id"], unique=False)
    op.create_index(op.f("ix_manualauthorization_verdict_hash"), "manualauthorization", ["verdict_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_manualauthorization_verdict_hash"), table_name="manualauthorization")
    op.drop_index(op.f("ix_manualauthorization_run_id"), table_name="manualauthorization")
    op.drop_index(op.f("ix_manualauthorization_patch_hash"), table_name="manualauthorization")
    op.drop_index(op.f("ix_manualauthorization_book_key"), table_name="manualauthorization")
    op.drop_index(op.f("ix_manualauthorization_authorization_id"), table_name="manualauthorization")
    op.drop_table("manualauthorization")
    # ### end Alembic commands ###
